### ISSUE TITLE
SOAP-UI v5.7.0 - OpenAPI Servers should be added as "Endpoints"

### ISSUE THREAD

**Issue by chatelao** [SmartBear/soapui#727]
Adding the servers as "Endpoints" would be easy & great:

Example: [openapi.yaml](https://vscode.dev/github/openbankingproject-ch/obp-apis/blob/fe49bf760a3fdae298c3585b3939ee9de1427105/swiss-ng-api.yam)

```yaml
servers:
  - url: https://api.dev.openbankingproject.ch
    description: Open Banking Project Switzerland Developer Portal
```
Goal:
- This values should be imported
