### ISSUE TITLE
SOAP-UI v5.7.0 - OpenAPI generate Property Transfer from Link

### ISSUE THREAD

**Issue by chatelao** [SmartBear/soapui#729]
Is:
- OpenAPI Links define exactly property transfers: https://swagger.io/docs/specification/links/

Should:
- Add a next step to a testcase by:
1. Right click on a Teststep
2. Choose the link to follow
3. => This adds a property transfer & the next request

```yaml
          # -----------------------------------------------------
          # Links
          # -----------------------------------------------------
          links:
            GetUserByUserId:   # <---- arbitrary name for the link
              operationId: getUser
              # or
              # operationRef: '#/paths/~1users~1{userId}/get'
              parameters:
                userId: '$response.body#/id'
              description: >
                The `id` value returned in the response can be used as
                the `userId` parameter in `GET /users/{userId}`.
          # -----------------------------------------------------
```
